# 서비스 정의
services:

  # web-server
  web-server:
    image: ${FE_IMAGE_NAME}:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/data:/var/www/certbot
      - ./certbot/conf:/etc/nginx/ssl
      - ./nginx/image-server/data/image_cache:/data/image_cache
    depends_on:
      - app

  # web-application-server
  app:
    image: ${BE_IMAGE_NAME}:latest
    ports:
      - 8080:8080
    environment:
      - DB_URL=${DB_URL_MAIN}
      - DB_DRIVER=${DB_DRIVER_MAIN}
      - DB_USERNAME=${DB_USERNAME_MAIN}
      - DB_PASSWORD=${DB_PASSWORD_MAIN}
      - REDIS_HOST=${REDIS_HOST_MAIN}
      - WEBCLIENT_BASE_URL=${WEBCLIENT_BASE_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_CREDENTIALS_ACCESS_KEY=${S3_CREDENTIALS_ACCESS_KEY}
      - S3_CREDENTIALS_SECRET_KEY=${S3_CREDENTIALS_SECRET_KEY}
      - RUNPOD_API_KEY=${RUNPOD_API_KEY}
      - RUNPOD_ENDPOINT_ID=${RUNPOD_ENDPOINT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TTS_API_KEY=${TTS_API_KEY}
      - PYTHON_IMAGE_SERVICE_URL=http://ai-service:8190
    depends_on:
      cache-server:
        condition: service_healthy
      ai-service:
        condition: service_started

  # AI 이미지 생성 서비스
  ai-service:
    image: ${AI_IMAGE_NAME}:latest
    ports:
      - 8190:8190
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AWS_ACCESS_KEY_ID=${S3_CREDENTIALS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_CREDENTIALS_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${S3_REGION}

  # cache-server
  cache-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5

  # coturn
  coturn:
    image: instrumentisto/coturn
    container_name: coturn
    restart: unless-stopped
    network_mode: "host"
    environment:
      - TURN_PORT=3478
      - TURNS_PORT=5349
      - TURN_USER=longagocoturn:longago123!
      - REALM=longago.io
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
      - ./data:/var/lib/turn
    command: ["turnserver", "-c", "/etc/coturn/turnserver.conf"]